version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: otpdb
      POSTGRES_USER: otpuser
      POSTGRES_PASSWORD: otppass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otpuser -d otpdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    environment:
      PORT: "8080"
      JWT_SECRET: "dev"
      # Postgres
      PG_URL: "postgres://otpuser:otppass@db:5432/otpdb?sslmode=disable"
      # Redis
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dbdata:
